### **Tensor**
In Machine Learning, a tensor is a general-purpose data structure used to represent and process numerical data.
You can think of it as an extension of scalars, vectors, and matrices to any number of dimensions.

    Tensor by dimensions
    Type	        Dimension	    Example
    Scalar	        0D	            5
    Vector	        1D	            [1, 2, 3]
    Matrix	        2D	            [[1,2], [3,4]]
    3D Tensor	3D	            Multiple matrices
    4D Tensor	4D	            Multiple 3D tensors

In [5]:
import numpy as np

In [14]:
# 0D Tensor/ Scaler
a = np.array(2)

In [17]:
a

array(2)

In [18]:
# 1D Tensor/ Vector

a = np.array([1,2,3,4])

In [19]:
a

array([1, 2, 3, 4])

In [20]:
# 2D Tensor / Matrix
mat = np.array([[1,2,3],[4,5,6],[7,8,9]])

In [21]:
mat

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [22]:
# 3D Tensor

Three = np.array([[[1,2,3],[5,6,7]],
                  [[4,5,6],[7,8,9]]])

In [24]:
Three

array([[[1, 2, 3],
        [5, 6, 7]],

       [[4, 5, 6],
        [7, 8, 9]]])